/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as agentsyncCmd } from './commands/agent-sync.ts';
import type { command as agentsyncInstallCmd } from './commands/agent-sync/install.ts';
import type { command as agentsyncStatusCmd } from './commands/agent-sync/status.ts';
import type { command as agentsyncSyncnowCmd } from './commands/agent-sync/sync-now.ts';
import type { command as agentsyncUninstallCmd } from './commands/agent-sync/uninstall.ts';
import type { command as backupCmd } from './commands/backup.ts';
import type { command as destroyCmd } from './commands/destroy.ts';
import type { command as doctorCmd } from './commands/doctor.ts';
import type { command as nangoCmd } from './commands/nango.ts';
import type { command as nangoIntegrationsAddCmd } from './commands/nango/integrations/add.ts';
import type { command as nangoIntegrationsCmd } from './commands/nango/integrations.ts';
import type { command as nangoIntegrationsDeployCmd } from './commands/nango/integrations/deploy.ts';
import type { command as nangoIntegrationsStatusCmd } from './commands/nango/integrations/status.ts';
import type { command as nangoRestoreCmd } from './commands/nango/restore.ts';
import type { command as openCmd } from './commands/open.ts';
import type { command as recoverCmd } from './commands/recover.ts';
import type { command as resizeCmd } from './commands/resize.ts';
import type { command as restoreCmd } from './commands/restore.ts';
import type { command as resumeCmd } from './commands/resume.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as setupCmd } from './commands/setup.ts';
import type { command as statusCmd } from './commands/status.ts';
import type { command as updateCmd } from './commands/update.ts';
import type { command as versionCmd } from './commands/version.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync install': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync status': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync sync-now': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync uninstall': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'backup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango integrations': {
      parents: {
        'nango': { options: InferForwardedOptions<typeof nangoCmd.options>; params: InferParams<typeof nangoCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango integrations add': {
      parents: {
        'nango': { options: InferForwardedOptions<typeof nangoCmd.options>; params: InferParams<typeof nangoCmd.params> };
        'nango integrations': { options: InferForwardedOptions<typeof nangoIntegrationsCmd.options>; params: InferParams<typeof nangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango integrations deploy': {
      parents: {
        'nango': { options: InferForwardedOptions<typeof nangoCmd.options>; params: InferParams<typeof nangoCmd.params> };
        'nango integrations': { options: InferForwardedOptions<typeof nangoIntegrationsCmd.options>; params: InferParams<typeof nangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango integrations status': {
      parents: {
        'nango': { options: InferForwardedOptions<typeof nangoCmd.options>; params: InferParams<typeof nangoCmd.params> };
        'nango integrations': { options: InferForwardedOptions<typeof nangoIntegrationsCmd.options>; params: InferParams<typeof nangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'nango restore': {
      parents: {
        'nango': { options: InferForwardedOptions<typeof nangoCmd.options>; params: InferParams<typeof nangoCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'open': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'recover': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'resize': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'restore': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'version': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'agent-sync': {
      segment: { kind: 'literal', value: 'agent-sync' },
      command: { path: 'agent-sync', load: () => import('./commands/agent-sync.ts').then((m) => m.command) },
      literalChildren: {
        'install': {
          segment: { kind: 'literal', value: 'install' },
          command: { path: 'agent-sync install', load: () => import('./commands/agent-sync/install.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'status': {
          segment: { kind: 'literal', value: 'status' },
          command: { path: 'agent-sync status', load: () => import('./commands/agent-sync/status.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'sync-now': {
          segment: { kind: 'literal', value: 'sync-now' },
          command: { path: 'agent-sync sync-now', load: () => import('./commands/agent-sync/sync-now.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'uninstall': {
          segment: { kind: 'literal', value: 'uninstall' },
          command: { path: 'agent-sync uninstall', load: () => import('./commands/agent-sync/uninstall.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'backup': {
      segment: { kind: 'literal', value: 'backup' },
      command: { path: 'backup', load: () => import('./commands/backup.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'destroy': {
      segment: { kind: 'literal', value: 'destroy' },
      command: { path: 'destroy', load: () => import('./commands/destroy.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'doctor': {
      segment: { kind: 'literal', value: 'doctor' },
      command: { path: 'doctor', load: () => import('./commands/doctor.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'nango': {
      segment: { kind: 'literal', value: 'nango' },
      command: { path: 'nango', load: () => import('./commands/nango.ts').then((m) => m.command) },
      literalChildren: {
        'integrations': {
          segment: { kind: 'literal', value: 'integrations' },
          command: { path: 'nango integrations', load: () => import('./commands/nango/integrations.ts').then((m) => m.command) },
          literalChildren: {
            'add': {
              segment: { kind: 'literal', value: 'add' },
              command: { path: 'nango integrations add', load: () => import('./commands/nango/integrations/add.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
            'deploy': {
              segment: { kind: 'literal', value: 'deploy' },
              command: { path: 'nango integrations deploy', load: () => import('./commands/nango/integrations/deploy.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
            'status': {
              segment: { kind: 'literal', value: 'status' },
              command: { path: 'nango integrations status', load: () => import('./commands/nango/integrations/status.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'restore': {
          segment: { kind: 'literal', value: 'restore' },
          command: { path: 'nango restore', load: () => import('./commands/nango/restore.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'open': {
      segment: { kind: 'literal', value: 'open' },
      command: { path: 'open', load: () => import('./commands/open.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'recover': {
      segment: { kind: 'literal', value: 'recover' },
      command: { path: 'recover', load: () => import('./commands/recover.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'resize': {
      segment: { kind: 'literal', value: 'resize' },
      command: { path: 'resize', load: () => import('./commands/resize.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'restore': {
      segment: { kind: 'literal', value: 'restore' },
      command: { path: 'restore', load: () => import('./commands/restore.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'resume': {
      segment: { kind: 'literal', value: 'resume' },
      command: { path: 'resume', load: () => import('./commands/resume.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'setup': {
      segment: { kind: 'literal', value: 'setup' },
      command: { path: 'setup', load: () => import('./commands/setup.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'status': {
      segment: { kind: 'literal', value: 'status' },
      command: { path: 'status', load: () => import('./commands/status.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'template': {
      segment: { kind: 'literal', value: 'template' },
      command: null,
      literalChildren: {},
      paramChild: null,
    },
    'update': {
      segment: { kind: 'literal', value: 'update' },
      command: { path: 'update', load: () => import('./commands/update.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'version': {
      segment: { kind: 'literal', value: 'version' },
      command: { path: 'version', load: () => import('./commands/version.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
